
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql:///nagato?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis-19852.c1.asia-northeast1-1.gce.cloud.redislabs.com
    port: 19852
    password: jwvx2wKN1UbiDpcowyQd7h58ieASF9eY
redis:
  channel:
    name: wangzisfa
logging:
  level:
    root: debug
mybatis:
  mapper-locations: classpath:mappers/*.xml
verification-code:
  from: wzh0131@gmail.com
  password: wangziheng2001
  min-send-interval: 60s
  expire-time: 30m